<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CrewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrewRepository extends EntityRepository
{
//    public function isUserInThisCrew($iduser)
//    {
//        $query = $this->getEntityManager()->createQuery(
//            "SELECT u FROM AppBundle:User u JOIN AppBundle:Crew i WHERE u.id = :iduser"
//        )->setParameter('iduser', $iduser)
//            ->getResult();
//        return $query;
//    }
}
