<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CrewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrewRepository extends EntityRepository
{
    public function findAllActive()
    {
        $dql = "SELECT c FROM AppBundle:Crew c WHERE c.accepted=1";
        $query = $this->getEntityManager()->createQuery($dql);
        
        return $query->getResult();
    }
    
}
