<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function findAllUsersSorted()
    {
        return $this->getEntityManager()->createQuery(
        "SELECT u FROM AppBundle:User u ORDER BY u.username ASC"
    )->getResult();
    }

    public function findAllCrews()
    {
        return $this->getEntityManager()->createQuery(
            "SELECT c FROM AppBundle:Crew c ORDER BY c.name ASC"
        )->getResult();
    }

    public function findAllEvents()
    {
        return $this->getEntityManager()->createQuery(
            "SELECT e FROM AppBundle:Event e ORDER BY e.name ASC"
        )->getResult();
    }
    
    public function findEventsNotAccepted()
    {
        return $this->getEntityManager()->createQuery(
            "SELECT e FROM AppBundle:Event e WHERE e.accepted = 0 ORDER BY e.name ASC"
        )->getResult();
    }

    public function findCrewsNotAccepted()
    {
        return $this->getEntityManager()->createQuery(
            "SELECT c FROM AppBundle:Crew c WHERE c.accepted = 0 ORDER BY c.name ASC"
        )->getResult();
    }
    
}
